---
repos:
  - repo: local
    hooks:
      - id: python-lint
        name: Python-lint
        description: This hook runs pylint.
        entry: pylint --exit-zero
        language: python
        files: \.(py)$
      - id: python-flake8
        name: Python Flake8
        description: This hook runs Flake8
        entry: flake8 --statistics
        language: python
        files: \.(py)$
